setup test
dev-romelus/front.bugreturn pull request #1
Opened 2022-08-12 05:24 UTC by dev-romelus

2022-08-12 05:31 UTC, dev-romelus commented on src/components/ui/Count.tsx
> +import { useState } from 'react';
Remove this file.

2022-08-12 05:32 UTC, dev-romelus commented on src/context/actions/auth.action.ts
> +import { ILogin, AuthDispatch } from '../../types/index';
Remove this file.

2022-08-12 05:32 UTC, dev-romelus commented on src/context/reducers/auth.reducer.ts
> +import { Action, IAuthState } from '../../types';
Remove this file.

2022-08-12 05:32 UTC, dev-romelus commented on src/context/reducers/index.ts
> +    authState: authReducer(states.authState, action),
remove this line.

2022-08-12 05:33 UTC, dev-romelus commented on src/context/states/index.ts
> +    authState: { isAuthenticated: false, isLoading: false },
remove this line.

2022-08-12 05:33 UTC, dev-romelus commented on src/context/types/auth.type.ts
> +export enum AuthType {
Remove this file.

2022-08-12 05:34 UTC, dev-romelus commented on src/context/types/notification.type.ts
> +export enum NotificationType {
Remove this file.

2022-08-12 06:55 UTC, dev-romelus commented on src/hooks/usePublicRoute.ts
> +import { useEffect } from 'react';
remove this file.

2022-08-12 08:05 UTC, dev-romelus commented on src/utils/enums/socket.enum.ts
> +export enum SocketEvents {
remove SEND_NOTIFICATION. add CREATE_NOTIFICATION and GET_NOTIFICATIONS

2022-08-12 08:37 UTC, app-robuste requested changes
Cf comments.

2022-08-15 10:07 UTC, app-robuste approved these changes

2022-08-15 10:07 UTC, merged